from django.urls import path
from apps.users.views import (
    MyProfileView,
    EditMyProfileView,
    UserSettingsView,
    PrivacySettingsView,
    ProfileStrengthView,
    PublicUserView,
    PublicProfileView,
    FollowUserView,
    UnfollowUserView,
    MuteUserView,
    UnmuteUserView,
    BlockUserView,
    UnblockUserView,
    SendConnectionRequestView,
    PendingConnectionsView,
    AcceptConnectionView,
    RejectConnectionView,
    FollowersListView,
    FollowingListView,
    ConnectionsListView,
)

urlpatterns = [
    path('me/profile/', MyProfileView.as_view()),
    path('me/profile/edit/', EditMyProfileView.as_view()),
    path('me/settings/', UserSettingsView.as_view()),
    path('me/privacy/', PrivacySettingsView.as_view()),
    path('me/profile-strength/', ProfileStrengthView.as_view()),
    path('<str:username>/', PublicUserView.as_view()),
    path('<str:username>/profile/', PublicProfileView.as_view()),
    path('<str:username>/follow/', FollowUserView.as_view()),
    path('<str:username>/unfollow/', UnfollowUserView.as_view()),
    path('<str:username>/mute/', MuteUserView.as_view()),
    path('<str:username>/unmute/', UnmuteUserView.as_view()),
    path('<str:username>/block/', BlockUserView.as_view()),
    path('<str:username>/unblock/', UnblockUserView.as_view()),
    path('<str:username>/connect/', SendConnectionRequestView.as_view()),
    path('connections/pending/', PendingConnectionsView.as_view()),
    path('connections/<str:username>/accept/', AcceptConnectionView.as_view()),
    path('connections/<str:username>/reject/', RejectConnectionView.as_view()),
    path('<str:username>/followers/', FollowersListView.as_view()),
    path('<str:username>/following/', FollowingListView.as_view()),
    path('<str:username>/connections/', ConnectionsListView.as_view()),
]
